# Generated by Django 5.0.3 on 2024-04-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
