# Generated by Django 5.0.3 on 2024-05-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cafeteria_favorita',
            field=models.ManyToManyField(blank=True, related_name='cafeterias_favoritas', to='coffee12app.estabelecimento'),
        ),
    ]
