# Generated by Django 5.0.3 on 2024-04-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0003_customuser_possui_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coffee12app.estabelecimento'),
        ),
    ]
