# Generated by Django 5.0.3 on 2024-04-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0005_prato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='em_promocao',
            new_name='preco_promocional',
        ),
    ]
