# Generated by Django 5.0.3 on 2024-06-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0005_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('numero_pessoas', models.IntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('AC', 'Aceito'), ('RE', 'Recusado')], default='PE', max_length=2)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee12app.estabelecimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
