# Generated by Django 5.0.3 on 2024-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0006_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('AC', 'Aceito'), ('RE', 'Recusado'), ('CA', 'Cancelado')], default='PE', max_length=2),
        ),
    ]
