# Generated by Django 5.0.3 on 2024-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0008_estabelecimento_descricao_horario_diasemana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='prato_principal',
            field=models.BooleanField(default=False),
        ),
    ]
