# Generated by Django 5.0.3 on 2024-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee12app', '0008_itemesquecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemesquecido',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('AC', 'Achado'), ('NE', 'Não Encontrado')], default='PE', max_length=2),
        ),
    ]
